### ISSUE TITLE
Error import check_internet

### ISSUE THREAD

**Issue by ashraful1980** [0p71mu5/md5-hash-decrypt#1]
Dear Sir,
Have a nice day and hope you are fine.

I have many tried to run "md5-hash-decrypt" software to python3 latest; but it was unable to run. As bellow error observe; please help: 
└─$ python3 md5-hash-decrypt.py 5f4dcc3b5aa765d61d8327deb882cf99
Traceback (most recent call last):
  File "/home/pc/md5-hash-decrypt/md5-hash-decrypt.py", line 12, in <module>
    import check_internet
ModuleNotFoundError: No module named 'check_internet'

![image](https://user-images.githubusercontent.com/52574658/108540912-ff4cf480-730b-11eb-9b8f-b614500bac83.png)

**Comment by 0p71mu5** [comment]
Uploaded the missing file check_internet.py
